In [ ]:
import pandas as pd
data = [10, 20, 30, 40, 50]
series = pd. Series (data)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
a = [1, 7, 21]
myvar = pd.Series (a, index = ["x", "y", "z"])
print (myvar)

x     1
y     7
z    21
dtype: int64

In [ ]:

gt=series > 25
print("series>25= \n",gt)
series_filtered = series [series > 25]
print("Filtered Series: \n", series_filtered)
series_multiplied = series * 2
print("\nSeries after Scalar Multiplication: \n", series_multiplied)

series>25=
 0    False
1    False
2     True
3     True
4     True
dtype: bool
Filtered Series:
 2    30
3    40
4    50
dtype: int64

Series after Scalar Multiplication:
 0     20
1     40
2     60
3     80
4    100
dtype: int64

In [ ]:
data = {
"calories": [420, 380, 390],
"duration": [50, 40, 45]
}
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop' : [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
print (frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [ ]:
frame = pd.DataFrame(data, columns=['year', 'state', 'pop'])
print(frame)

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print(frame2)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print (frame2 ['year'])

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print("\n", frame2['state'])

 one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print("\n", frame2.state)

 one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print (frame2.loc['one'])

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [ ]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five', 'six'])
print (frame2.loc[['two', 'three']])

       year state  pop debt
two    2001  Ohio  1.7  NaN
three  2002  Ohio  3.6  NaN

In [ ]:
frame2 ['debt'] = 12.4
print (frame2)

       year   state  pop  debt
one    2000    Ohio  1.5  12.4
two    2001    Ohio  1.7  12.4
three  2002    Ohio  3.6  12.4
four   2001  Nevada  2.4  12.4
five   2002  Nevada  2.9  12.4
six    2003  Nevada  3.2  12.4

In [ ]:
import numpy as np
frame2 ['debt'] = np.arange(6.)
print (frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [ ]:
val = pd.Series ([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['debt'] = val
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [ ]:
frame2 ['eastern'] = frame2.state = 'Ohio'
print(frame2)

       year state  pop  debt eastern
one    2000  Ohio  1.5   NaN    Ohio
two    2001  Ohio  1.7  -1.2    Ohio
three  2002  Ohio  3.6   NaN    Ohio
four   2001  Ohio  2.4  -1.5    Ohio
five   2002  Ohio  2.9  -1.7    Ohio
six    2003  Ohio  3.2   NaN    Ohio

In [ ]:
del frame2 ['eastern']
print(frame2)

       year state  pop  debt
one    2000  Ohio  1.5   NaN
two    2001  Ohio  1.7  -1.2
three  2002  Ohio  3.6   NaN
four   2001  Ohio  2.4  -1.5
five   2002  Ohio  2.9  -1.7
six    2003  Ohio  3.2   NaN

In [ ]:
print (frame2.T)

        one   two three  four  five   six
year   2000  2001  2002  2001  2002  2003
state  Ohio  Ohio  Ohio  Ohio  Ohio  Ohio
pop     1.5   1.7   3.6   2.4   2.9   3.2
debt    NaN  -1.2   NaN  -1.5  -1.7   NaN

In [ ]:
obj = pd. Series ([4.5, 7.2, -5.3, 3.6], index= ['d', 'b', 'a', 'c'])
print(obj)
obj2= obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
print(obj3)

obj4= obj3. reindex (range(6), method='ffill') #forward-fills the values
obj4

0      blue
2    purple
4    yellow
dtype: object

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj4= obj3. reindex (range(6), method='ffill')
print("Method 'ffill':")
print(obj4)

obj5 = obj3. reindex (range(6), method='bfill')
print("\nMethod 'bfill':")
print(obj5)

obj6 = obj3. reindex (range(6), fill_value='red')
print("\nFill value:")
print(obj6)

obj7 = pd.Series([1, 2, 3], index=[0, 2, 51])
obj8= obj7. reindex (range(7), method='ffill', limit=1)
print("\nLimit:")
print(obj8)

Method 'ffill':
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

Method 'bfill':
0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

Fill value:
0      blue
1       red
2    purple
3       red
4    yellow
5       red
dtype: object

Limit:
0    1.0
1    1.0
2    2.0
3    2.0
4    NaN
5    NaN
6    NaN
dtype: float64

In [ ]:
obj = pd.Series (np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
print(new_obj)
obj.drop(['d', 'c'])

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

a    0.0
b    1.0
e    4.0
dtype: float64

In [ ]:
df = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Dallas', 'NJ', 'New York'], columns=['one', 'two', 'three', 'four'])

          one  two  three  four
Ohio        0    1      2     3
Dallas      4    5      6     7
NJ          8    9     10    11
New York   12   13     14    15

In [6]:
import pandas as pd
import numpy as np
obj = pd.Series (np.arange(4.), index=['a', 'b', 'c', 'd'])
print("obj ['b']= \n",obj ['b'])
print("obj [1]= \n", obj [1])
print("obj [2:4]= \n",obj [2:4])
print("obj [['b', 'a', 'd']]= \n", obj [['b', 'a', 'd']])
print("obj [b:d]= \n",obj ['b': 'd']) #no n-1 concept
print("obj [[1, 3]]= \n", obj [[1, 3]])
print("obj [obj < 2]= \n", obj [obj < 2])

obj ['b']=
 1.0
obj [1]=
 1.0
obj [2:4]=
 c    2.0
d    3.0
dtype: float64
obj [['b', 'a', 'd']]=
 b    1.0
a    0.0
d    3.0
dtype: float64
obj [b:d]=
 b    1.0
c    2.0
d    3.0
dtype: float64
obj [[1, 3]]=
 b    1.0
d    3.0
dtype: float64
obj [obj < 2]=
 a    0.0
b    1.0
dtype: float64

/tmp/ipython-input-6-4115590071.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("obj [1]= \n", obj [1])
/tmp/ipython-input-6-4115590071.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("obj [[1, 3]]= \n", obj [[1, 3]])

In [8]:
data = pd.DataFrame(np.arange(24).reshape((6, 4)),
index=['Ohio', 'Dallas', 'Boston', 'NJ', 'New York', 'Austin'], columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Dallas      4    5      6     7
Boston      8    9     10    11
NJ         12   13     14    15
New York   16   17     18    19
Austin     20   21     22    23

In [9]:
data.loc['Dallas', ['two', 'three']]
data.at['Dallas', 'one']
np.int64(4)

np.int64(4)

In [10]:
data.iloc[3]

one      12
two      13
three    14
four     15
Name: NJ, dtype: int64

In [11]:
data.iloc[2:5,0:2]

          one  two
Boston      8    9
NJ         12   13
New York   16   17

In [12]:
data.iloc[1:4, :]

        one  two  three  four
Dallas    4    5      6     7
Boston    8    9     10    11
NJ       12   13     14    15

In [13]:
print(data.three>5)
data[data.three>5]

Ohio        False
Dallas       True
Boston       True
NJ           True
New York     True
Austin       True
Name: three, dtype: bool

          one  two  three  four
Dallas      4    5      6     7
Boston      8    9     10    11
NJ         12   13     14    15
New York   16   17     18    19
Austin     20   21     22    23

In [14]:
data<5
data[data<5]=0
data

          one  two  three  four
Ohio        0    0      0     0
Dallas      0    5      6     7
Boston      8    9     10    11
NJ         12   13     14    15
New York   16   17     18    19
Austin     20   21     22    23

In [17]:
df1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
df2=pd.DataFrame({'A':[7,8,9],'B':[10,11,12]})
print(df1+df2)
print(df1-df2)
print(df1*df2)
print(df1/df2)

    A   B
0   8  14
1  10  16
2  12  18
   A  B
0 -6 -6
1 -6 -6
2 -6 -6
    A   B
0   7  40
1  16  55
2  27  72
          A         B
0  0.142857  0.400000
1  0.250000  0.454545
2  0.333333  0.500000

In [19]:
df1=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]},index=[0,1,2])
df2=pd.DataFrame({'A':[7,8,9],'B':[10,11,12]},index=[1,2,3])
result=df1+df2
print(result)

      A     B
0   NaN   NaN
1   9.0  15.0
2  11.0  17.0
3   NaN   NaN

In [20]:
r=df1.add(df2,fill_value=0)
print(r)

      A     B
0   1.0   4.0
1   9.0  15.0
2  11.0  17.0
3   9.0  12.0

In [23]:
odj=pd.Series(range(4),index=['d','a','b','c'])
df_sort_series=obj.sort_index()
print(df_sort_series)
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])
df_sort_dataframe=frame.sort_index()
print(df_sort_dataframe)
df_sort_dataframe_axis1=frame.sort_index(axis=1)
print(df_sort_dataframe_axis1)
df_sort_dataframe_ascending=frame.sort_index(axis=1,ascending=False)
print(df_sort_dataframe_ascending)
df_sort_values_by_column=frame.sort_values(by='b')
print(df_sort_values_by_column)

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
       a  b  c  d
three  1  2  3  0
one    5  6  7  4
       d  c  b  a
three  0  3  2  1
one    4  7  6  5
       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [27]:
obj=pd.Series([7,-5,7,3,2,0,4])
df_rank=obj.rank()
print(df_rank)
df_rank_method=obj.rank(method='first')
print(df_rank_method)
df_rank_ascending=obj.rank(ascending=False,method='max')
print(df_rank_ascending)
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})
print(frame)
df_rank_dataframe=frame.rank(axis='columns')
print(df_rank_dataframe)

0    6.5
1    1.0
2    6.5
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    3.0
dtype: float64
     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5
     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0